declare module 'rollup-plugin-babel';
declare module 'rollup-plugin-node-resolve';
declare module 'rollup-plugin-commonjs';
declare module 'rollup-plugin-postcss';
declare module 'autoprefixer';
// declare module 'lodash.merge';
declare module '@babel/core';
declare module 'slash2';
declare module 'sort-package-json';
declare module 'path-is-root';
declare module 'temp-dir';
